### ISSUE TITLE
Weapons

### ISSUE THREAD

**Issue by sarahbau** [enj/dnd#10]

**Comment by enj** [comment]
1. Input box to choose dice count int [1,20]
2. Drop down for dice type
3. Drop down for attribute
4. Use 1 to 3 to calculate hit dice bonus (attribute bonus + proficiency bonus)
5. Use 1 to 3 to calculate damage (n \* dice + attribute bonus)
6. Additional bonus

**Comment by DewHunter** [comment]
Do i leave weight in there?

**Comment by DewHunter** [comment]
showing info looks awful, we should probably not show dice count and type
or maybe, idk haha

**Comment by sarahbau** [comment]
I think this is good now.
