### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by sarahbau** [enj/dnd#15]

**Comment by sarahbau** [comment]
@DewHunter this can basically be a copy of armor, possibly having an optional value (money value) instead of the armor field.

**Comment by DewHunter** [comment]
Ok Gotcha!

**Comment by DewHunter** [comment]
Can we close?

**Comment by enj** [comment]
@sarahbau I am good with this, please close it if you are happy

**Comment by sarahbau** [comment]
No edit functionality
