### ISSUE TITLE
Character Background

### ISSUE THREAD

**Issue by sarahbau** [enj/dnd#7]

**Comment by sarahbau** [comment]
Fix 270px wide text box. make 100% with padding

**Comment by sarahbau** [comment]
Fix white border around title box

**Comment by enj** [comment]
Center edit button

**Comment by DewHunter** [comment]
can we close?

**Comment by enj** [comment]
Just remove the floating label and then you are good.

**Comment by sarahbau** [comment]
Make dialog box larger

**Comment by sarahbau** [comment]
This issue needs another comment. I think the edit button should be on the left rather than centered, to match other buttons

**Comment by sarahbau** [comment]
Moved button to the left
